name: la_corniche
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-313.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5  
  google_fonts: ^4.0.3
  table_calendar: ^3.0.9  
  provider: ^6.0.5
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/chambreAffaire.jpg
    - images/chambreEconomique.jpg
    - images/chambreStanding.jpg
    - images/chambreNormal.jpg
    - images/background.jpg
    - images/background1.jpg
    - images/background3.jpg
